name: tobby_reviewer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  get_it: ^7.6.6
  uuid: ^4.2.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#42a5f5"
  image: "assets/splash_logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - lib/core/data/data_source/local_exam_data/
    - assets/images/
    - assets/icons/
